# Generated by Django 3.2.16 on 2022-12-29 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PetitionApp', '0004_petitionmodel_signcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP пользователя')),
                ('petCategory', models.CharField(blank=True, max_length=512, null=True, verbose_name='Тип страницы')),
                ('date_view', models.DateTimeField(auto_now_add=True, verbose_name='Дата просмотра')),
                ('petition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PetitionApp.petitionmodel', verbose_name='Петиция')),
            ],
            options={
                'verbose_name': 'Посещения',
                'verbose_name_plural': 'Посещения',
            },
        ),
    ]
