# Generated by Django 3.2.16 on 2022-12-28 21:26

import PetitionApp.models
import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PetitionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetitionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Наименование петиции')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to=PetitionApp.models.PetitionModel.get_file_path, verbose_name='Картинка петции')),
                ('dateCreate', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания записи')),
                ('dateStart', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Дата начала петиции')),
                ('dateEnd', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Дата завершения петиции')),
                ('author', models.CharField(blank=True, max_length=512, null=True, verbose_name='Автор петиции')),
                ('authorEmail', models.CharField(blank=True, max_length=256, null=True, verbose_name='Email Автора петиции')),
                ('authorContact', models.CharField(blank=True, max_length=256, null=True, verbose_name='Контактные данные автора петици')),
                ('signSum', models.IntegerField(default=1, verbose_name='Заказанное количество подписей')),
                ('onMain', models.BooleanField(default=False, verbose_name='Вывести на главный баннер')),
                ('status', models.BooleanField(default=False, verbose_name='Статус отображения на сайте')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PetitionApp.petitoncategorymodel', verbose_name='Категория петиции')),
            ],
            options={
                'verbose_name': 'Петциия',
                'verbose_name_plural': 'Петции',
            },
        ),
    ]
