# Generated by Django 3.2.16 on 2022-12-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetitionApp', '0002_petitionmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petitionmodel',
            old_name='category',
            new_name='petCategory',
        ),
    ]
