# Generated by Django 3.2.16 on 2022-12-29 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SignApp', '0001_initial'),
        ('PetitionApp', '0003_rename_category_petitionmodel_petcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='petitionmodel',
            name='signCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SignApp.signcategorymodel', verbose_name='Метод идентификации'),
        ),
    ]
