# Generated by Django 3.2.16 on 2022-12-28 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RespondentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=250, verbose_name='Имя')),
                ('secondName', models.CharField(max_length=250, verbose_name='Фамилия')),
                ('identifyNumber', models.CharField(max_length=12, verbose_name='ИИН/БИН')),
                ('mobileNumber', models.CharField(max_length=11, verbose_name='Мобильный номер')),
                ('email', models.EmailField(blank=True, max_length=120, null=True, verbose_name='email')),
                ('dateCreate', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания записи')),
                ('status', models.BooleanField(default=True, verbose_name='Актуальность данных')),
            ],
            options={
                'verbose_name': 'Респондент',
                'verbose_name_plural': 'Респонденты',
            },
        ),
    ]
