# Generated by Django 3.2.16 on 2022-12-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Наименование категории')),
                ('inlineCode', models.CharField(max_length=512, verbose_name='Наименование (системно)')),
                ('status', models.BooleanField(default=False, verbose_name='Активация')),
            ],
            options={
                'verbose_name': 'Метод идентификации',
                'verbose_name_plural': 'Методы идентификации',
            },
        ),
    ]
