# Generated by Django 3.2.16 on 2022-12-29 17:12

import SignApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
        ('PetitionApp', '0004_petitionmodel_signcategory'),
        ('SignApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignIdentificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liveness3d', models.ImageField(blank=True, null=True, upload_to=SignApp.models.SignIdentificationModel.get_file_path, verbose_name='Фото биометрия')),
                ('redirect_code', models.CharField(blank=True, max_length=500, verbose_name='Данные пользователя (зашифрованные данные)')),
                ('access_token', models.CharField(blank=True, max_length=1200, verbose_name='Access_token')),
                ('doc1', models.FileField(blank=True, null=True, upload_to=SignApp.models.SignIdentificationModel.get_file_path, verbose_name='Петииця на подпись')),
                ('signId1', models.IntegerField(default=2021, null=True, verbose_name='ИД загруженного документа в service')),
                ('signSms1', models.IntegerField(default=2021, null=True, verbose_name='SMS для идентификации')),
                ('signSmsId1', models.CharField(max_length=256, null=True, verbose_name='ID SMS идентификации')),
                ('doc1s', models.FileField(blank=True, null=True, upload_to=SignApp.models.SignIdentificationModel.get_file_path, verbose_name='Петиция (Подписанный)')),
                ('signStatus', models.BooleanField(default=False, verbose_name='Статус подписания')),
                ('signDate', models.DateField(blank=True, null=True, verbose_name='Дата подписи')),
                ('identificationMethod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SignApp.signcategorymodel', verbose_name='Метод идентификации')),
                ('petition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PetitionApp.petitionmodel', verbose_name='Петиция')),
                ('respondent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.respondentmodel', verbose_name='Респондент')),
            ],
            options={
                'verbose_name': 'Идентитфикация и подпись',
                'verbose_name_plural': 'Идентитфикация и подпись',
            },
        ),
    ]
