# Generated by Django 3.2.16 on 2022-12-29 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
        ('PetitionApp', '0004_petitionmodel_signcategory'),
        ('SignApp', '0002_signidentificationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdd', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписания петиции')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес респондента')),
                ('status', models.BooleanField(default=True, verbose_name='Результат подписи')),
                ('petition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PetitionApp.petitionmodel', verbose_name='Петиция')),
                ('respondent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.respondentmodel', verbose_name='Респондент')),
                ('signCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SignApp.signcategorymodel', verbose_name='Метод идентификации')),
                ('signIdentification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SignApp.signidentificationmodel', verbose_name='Идентификация пользователя')),
            ],
            options={
                'verbose_name': 'Подписанные петиции',
                'verbose_name_plural': 'Подписанные петиции',
            },
        ),
    ]
